version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: infra-portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker-containers/infra-stack/portainer-data:/data
    networks:
      - default
      - proxy-tier

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: infra-proxy
    restart: unless-stopped
    ports:
      - '80:80'    # Public HTTP Port
      - '443:443'  # Public HTTPS Port
      - '81:81'    # NPM Management Web UI Port
    volumes:
      - ./proxy-data:/data
      - ./proxy-letsencrypt:/etc/letsencrypt
    networks:
      - default
      - proxy-tier

networks:
  proxy-tier:
    external: true
